apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: duoc-eks-cluster-cli
  region: us-east-1
  version: "1.31"

iam:
  serviceRoleARN: arn:aws:iam::533267352641:role/LabRole

managedNodeGroups:
  - name: ng-default
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    iam:
      instanceRoleARN: arn:aws:iam::533267352641:role/LabRole
    labels:
      role: worker
    tags:
      nodegroup-name: ng-default
